apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-boot
spec:
  host: spring-boot-pipelines-tutorial.apps.lab01.gpslab.club
  port:
    targetPort: 8080
  to:
    kind: Service
    name: spring-boot
